package tree

import (
	"context"
	"testing"
)

// TestTraverse_GrandPlazaHotel reproduces a customer report: when the
// property's location tree is walked with Traverse, at least one node is
// silently skipped — its callback never fires.
//
// With the data below, Traverse should invoke the callback once for every
// location in the fixture. It doesn't.
//
// This test currently fails. Diagnose why and fix it.
func TestTraverse_GrandPlazaHotel(t *testing.T) {
	// Sequence values are set on Floor 1's children to keep the traversal
	// order stable across sort implementations, so the failure is
	// deterministic and easy to reason about.
	locations := []Location{
		{ID: 1, Name: "Grand Plaza Hotel", LocationType: "Property"},
		{ID: 2, Name: "Floor 6", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 3, Name: "Basement", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 4, Name: "Floor 1", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 5, Name: "Floor 9", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 6, Name: "Ground Floor", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 7, Name: "Floor 3", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 8, Name: "Rooftop", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 9, Name: "Mezzanine", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 10, Name: "Floor 5", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 11, Name: "Floor 8", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 12, Name: "Floor 10", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 13, Name: "Floor 2", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 14, Name: "Floor 4", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 15, Name: "Floor 7", ParentID: ptr(1), LocationType: "Floor"},
		{ID: 16, Name: "East Wing", ParentID: ptr(7), LocationType: "Section"},
		{ID: 17, Name: "West Wing", ParentID: ptr(7), LocationType: "Section"},
		{ID: 18, Name: "Housekeeping Closet", ParentID: ptr(7), LocationType: "Storage"},
		{ID: 19, Name: "301", ParentID: ptr(16), LocationType: "Room"},
		{ID: 20, Name: "302", ParentID: ptr(16), LocationType: "Room"},
		{ID: 21, Name: "303", ParentID: ptr(16), LocationType: "Room"},
		{ID: 22, Name: "304", ParentID: ptr(16), LocationType: "Room"},
		{ID: 23, Name: "305", ParentID: ptr(16), LocationType: "Room"},
		{ID: 24, Name: "306", ParentID: ptr(17), LocationType: "Room"},
		{ID: 25, Name: "307", ParentID: ptr(17), LocationType: "Room"},
		{ID: 26, Name: "308", ParentID: ptr(17), LocationType: "Room"},
		{ID: 27, Name: "309", ParentID: ptr(17), LocationType: "Room"},
		{ID: 28, Name: "310", ParentID: ptr(17), LocationType: "Room"},
		{ID: 29, Name: "Loading Dock", ParentID: ptr(3), LocationType: "Section"},
		{ID: 30, Name: "Main Kitchen", ParentID: ptr(3), LocationType: "Section"},
		{ID: 31, Name: "Cold Storage", ParentID: ptr(3), LocationType: "Storage"},
		{ID: 32, Name: "Dry Storage", ParentID: ptr(3), LocationType: "Storage"},
		{ID: 33, Name: "Laundry", ParentID: ptr(3), LocationType: "Section"},
		{ID: 34, Name: "Maintenance Workshop", ParentID: ptr(3), LocationType: "Section"},
		{ID: 35, Name: "Staff Lounge", ParentID: ptr(3), LocationType: "Section"},
		{ID: 36, Name: "HR Office", ParentID: ptr(3), LocationType: "Section"},
		{ID: 37, Name: "Security Office", ParentID: ptr(3), LocationType: "Section"},
		{ID: 38, Name: "East Wing", ParentID: ptr(15), LocationType: "Section"},
		{ID: 39, Name: "West Wing", ParentID: ptr(15), LocationType: "Section"},
		{ID: 40, Name: "Housekeeping Closet", ParentID: ptr(15), LocationType: "Storage"},
		{ID: 41, Name: "701", ParentID: ptr(38), LocationType: "Room"},
		{ID: 42, Name: "702", ParentID: ptr(38), LocationType: "Room"},
		{ID: 43, Name: "703", ParentID: ptr(38), LocationType: "Room"},
		{ID: 44, Name: "704", ParentID: ptr(38), LocationType: "Room"},
		{ID: 45, Name: "705", ParentID: ptr(38), LocationType: "Room"},
		{ID: 46, Name: "706", ParentID: ptr(39), LocationType: "Room"},
		{ID: 47, Name: "707", ParentID: ptr(39), LocationType: "Room"},
		{ID: 48, Name: "708", ParentID: ptr(39), LocationType: "Room"},
		{ID: 49, Name: "709", ParentID: ptr(39), LocationType: "Room"},
		{ID: 50, Name: "710", ParentID: ptr(39), LocationType: "Room"},
		{ID: 51, Name: "Reception", ParentID: ptr(6), LocationType: "Section"},
		{ID: 52, Name: "Concierge", ParentID: ptr(6), LocationType: "Section"},
		{ID: 53, Name: "Main Lobby", ParentID: ptr(6), LocationType: "Section"},
		{ID: 54, Name: "Lobby Bar", ParentID: ptr(6), LocationType: "Section"},
		{ID: 55, Name: "Harbour Restaurant", ParentID: ptr(6), LocationType: "Section"},
		{ID: 56, Name: "Business Center", ParentID: ptr(6), LocationType: "Section"},
		{ID: 57, Name: "Gift Shop", ParentID: ptr(6), LocationType: "Section"},
		{ID: 58, Name: "Cloakroom", ParentID: ptr(6), LocationType: "Storage"},
		{ID: 59, Name: "East Wing", ParentID: ptr(4), LocationType: "Section", Sequence: 1},
		{ID: 60, Name: "West Wing", ParentID: ptr(4), LocationType: "Section", Sequence: 3},
		{ID: 61, Name: "Housekeeping Closet", ParentID: ptr(4), LocationType: "Storage", Sequence: 4},
		{ID: 62, Name: "101", ParentID: ptr(59), LocationType: "Room"},
		{ID: 63, Name: "102", ParentID: ptr(59), LocationType: "Room"},
		{ID: 64, Name: "103", ParentID: ptr(59), LocationType: "Room"},
		{ID: 65, Name: "104", ParentID: ptr(59), LocationType: "Room"},
		{ID: 66, Name: "105", ParentID: ptr(59), LocationType: "Room"},
		{ID: 67, Name: "106", ParentID: ptr(60), LocationType: "Room"},
		{ID: 68, Name: "107", ParentID: ptr(60), LocationType: "Room"},
		{ID: 69, Name: "108", ParentID: ptr(60), LocationType: "Room"},
		{ID: 70, Name: "109", ParentID: ptr(60), LocationType: "Room"},
		{ID: 71, Name: "110", ParentID: ptr(60), LocationType: "Room"},
		{ID: 72, Name: "East Wing", ParentID: ptr(5), LocationType: "Section"},
		{ID: 73, Name: "West Wing", ParentID: ptr(5), LocationType: "Section"},
		{ID: 74, Name: "Housekeeping Closet", ParentID: ptr(5), LocationType: "Storage"},
		{ID: 75, Name: "901", ParentID: ptr(72), LocationType: "Room"},
		{ID: 76, Name: "902", ParentID: ptr(72), LocationType: "Room"},
		{ID: 77, Name: "903", ParentID: ptr(72), LocationType: "Room"},
		{ID: 78, Name: "904", ParentID: ptr(72), LocationType: "Room"},
		{ID: 79, Name: "905", ParentID: ptr(72), LocationType: "Room"},
		{ID: 80, Name: "906", ParentID: ptr(73), LocationType: "Room"},
		{ID: 81, Name: "907", ParentID: ptr(73), LocationType: "Room"},
		{ID: 82, Name: "908", ParentID: ptr(73), LocationType: "Room"},
		{ID: 83, Name: "909", ParentID: ptr(73), LocationType: "Room"},
		{ID: 84, Name: "910", ParentID: ptr(73), LocationType: "Room"},
		{ID: 85, Name: "Ballroom A", ParentID: ptr(9), LocationType: "Section"},
		{ID: 86, Name: "Ballroom B", ParentID: ptr(9), LocationType: "Section"},
		{ID: 87, Name: "Meeting Room 1", ParentID: ptr(9), LocationType: "Section"},
		{ID: 88, Name: "Meeting Room 2", ParentID: ptr(9), LocationType: "Section"},
		{ID: 89, Name: "Meeting Room 3", ParentID: ptr(9), LocationType: "Section"},
		{ID: 90, Name: "Pre-function", ParentID: ptr(9), LocationType: "Section"},
		{ID: 91, Name: "Service Kitchen", ParentID: ptr(9), LocationType: "Section"},
		{ID: 92, Name: "East Wing", ParentID: ptr(10), LocationType: "Section"},
		{ID: 93, Name: "West Wing", ParentID: ptr(10), LocationType: "Section"},
		{ID: 94, Name: "Housekeeping Closet", ParentID: ptr(10), LocationType: "Storage"},
		{ID: 95, Name: "501", ParentID: ptr(92), LocationType: "Room"},
		{ID: 96, Name: "502", ParentID: ptr(92), LocationType: "Room"},
		{ID: 97, Name: "503", ParentID: ptr(92), LocationType: "Room"},
		{ID: 98, Name: "504", ParentID: ptr(92), LocationType: "Room"},
		{ID: 99, Name: "505", ParentID: ptr(92), LocationType: "Room"},
		{ID: 100, Name: "506", ParentID: ptr(93), LocationType: "Room"},
		{ID: 101, Name: "507", ParentID: ptr(93), LocationType: "Room"},
		{ID: 102, Name: "508", ParentID: ptr(93), LocationType: "Room"},
		{ID: 103, Name: "509", ParentID: ptr(93), LocationType: "Room"},
		{ID: 104, Name: "510", ParentID: ptr(93), LocationType: "Room"},
		{ID: 105, Name: "East Wing", ParentID: ptr(12), LocationType: "Section"},
		{ID: 106, Name: "West Wing", ParentID: ptr(12), LocationType: "Section"},
		{ID: 107, Name: "Housekeeping Closet", ParentID: ptr(12), LocationType: "Storage"},
		{ID: 108, Name: "1001", ParentID: ptr(105), LocationType: "Room"},
		{ID: 109, Name: "1002", ParentID: ptr(105), LocationType: "Room"},
		{ID: 110, Name: "1003", ParentID: ptr(105), LocationType: "Room"},
		{ID: 111, Name: "1004", ParentID: ptr(105), LocationType: "Room"},
		{ID: 112, Name: "1005", ParentID: ptr(105), LocationType: "Room"},
		{ID: 113, Name: "1006", ParentID: ptr(106), LocationType: "Room"},
		{ID: 114, Name: "1007", ParentID: ptr(106), LocationType: "Room"},
		{ID: 115, Name: "1008", ParentID: ptr(106), LocationType: "Room"},
		{ID: 116, Name: "1009", ParentID: ptr(106), LocationType: "Room"},
		{ID: 117, Name: "1010", ParentID: ptr(106), LocationType: "Room"},
		{ID: 118, Name: "East Wing", ParentID: ptr(14), LocationType: "Section"},
		{ID: 119, Name: "West Wing", ParentID: ptr(14), LocationType: "Section"},
		{ID: 120, Name: "Housekeeping Closet", ParentID: ptr(14), LocationType: "Storage"},
		{ID: 121, Name: "401", ParentID: ptr(118), LocationType: "Room"},
		{ID: 122, Name: "402", ParentID: ptr(118), LocationType: "Room"},
		{ID: 123, Name: "403", ParentID: ptr(118), LocationType: "Room"},
		{ID: 124, Name: "404", ParentID: ptr(118), LocationType: "Room"},
		{ID: 125, Name: "405", ParentID: ptr(118), LocationType: "Room"},
		{ID: 126, Name: "406", ParentID: ptr(119), LocationType: "Room"},
		{ID: 127, Name: "407", ParentID: ptr(119), LocationType: "Room"},
		{ID: 128, Name: "408", ParentID: ptr(119), LocationType: "Room"},
		{ID: 129, Name: "409", ParentID: ptr(119), LocationType: "Room"},
		{ID: 130, Name: "410", ParentID: ptr(119), LocationType: "Room"},
		{ID: 131, Name: "Pool Deck", ParentID: ptr(8), LocationType: "Section"},
		{ID: 132, Name: "Sky Bar", ParentID: ptr(8), LocationType: "Section"},
		{ID: 133, Name: "Spa", ParentID: ptr(8), LocationType: "Section"},
		{ID: 134, Name: "Gym", ParentID: ptr(8), LocationType: "Section"},
		{ID: 135, Name: "Pool Equipment", ParentID: ptr(8), LocationType: "Storage"},
		{ID: 136, Name: "East Wing", ParentID: ptr(11), LocationType: "Section"},
		{ID: 137, Name: "West Wing", ParentID: ptr(11), LocationType: "Section"},
		{ID: 138, Name: "Housekeeping Closet", ParentID: ptr(11), LocationType: "Storage"},
		{ID: 139, Name: "801", ParentID: ptr(136), LocationType: "Room"},
		{ID: 140, Name: "802", ParentID: ptr(136), LocationType: "Room"},
		{ID: 141, Name: "803", ParentID: ptr(136), LocationType: "Room"},
		{ID: 142, Name: "804", ParentID: ptr(136), LocationType: "Room"},
		{ID: 143, Name: "805", ParentID: ptr(136), LocationType: "Room"},
		{ID: 144, Name: "806", ParentID: ptr(137), LocationType: "Room"},
		{ID: 145, Name: "807", ParentID: ptr(137), LocationType: "Room"},
		{ID: 146, Name: "808", ParentID: ptr(137), LocationType: "Room"},
		{ID: 147, Name: "809", ParentID: ptr(137), LocationType: "Room"},
		{ID: 148, Name: "810", ParentID: ptr(137), LocationType: "Room"},
		{ID: 149, Name: "East Wing", ParentID: ptr(13), LocationType: "Section"},
		{ID: 150, Name: "West Wing", ParentID: ptr(13), LocationType: "Section"},
		{ID: 151, Name: "Housekeeping Closet", ParentID: ptr(13), LocationType: "Storage"},
		{ID: 152, Name: "201", ParentID: ptr(149), LocationType: "Room"},
		{ID: 153, Name: "202", ParentID: ptr(149), LocationType: "Room"},
		{ID: 154, Name: "203", ParentID: ptr(149), LocationType: "Room"},
		{ID: 155, Name: "204", ParentID: ptr(149), LocationType: "Room"},
		{ID: 156, Name: "205", ParentID: ptr(149), LocationType: "Room"},
		{ID: 157, Name: "206", ParentID: ptr(150), LocationType: "Room"},
		{ID: 158, Name: "207", ParentID: ptr(150), LocationType: "Room"},
		{ID: 159, Name: "208", ParentID: ptr(150), LocationType: "Room"},
		{ID: 160, Name: "209", ParentID: ptr(150), LocationType: "Room"},
		{ID: 161, Name: "210", ParentID: ptr(150), LocationType: "Room"},
		{ID: 162, Name: "East Wing", ParentID: ptr(2), LocationType: "Section"},
		{ID: 163, Name: "West Wing", ParentID: ptr(2), LocationType: "Section"},
		{ID: 164, Name: "Housekeeping Closet", ParentID: ptr(2), LocationType: "Storage"},
		{ID: 165, Name: "601", ParentID: ptr(162), LocationType: "Room"},
		{ID: 166, Name: "602", ParentID: ptr(162), LocationType: "Room"},
		{ID: 167, Name: "603", ParentID: ptr(162), LocationType: "Room"},
		{ID: 168, Name: "604", ParentID: ptr(162), LocationType: "Room"},
		{ID: 169, Name: "605", ParentID: ptr(162), LocationType: "Room"},
		{ID: 170, Name: "606", ParentID: ptr(163), LocationType: "Room"},
		{ID: 171, Name: "607", ParentID: ptr(163), LocationType: "Room"},
		{ID: 172, Name: "608", ParentID: ptr(163), LocationType: "Room"},
		{ID: 173, Name: "609", ParentID: ptr(163), LocationType: "Room"},
		{ID: 174, Name: "610", ParentID: ptr(163), LocationType: "Room"},
		{ID: 175, Name: "East Wing", ParentID: ptr(4), LocationType: "Storage", Sequence: 2},
	}

	_, root, err := BuildTree(locations)
	if err != nil {
		t.Fatalf("BuildTree returned error: %v", err)
	}

	visited := 0
	err = Traverse(context.Background(), root, map[string]bool{}, func(n *Node) error {
		visited++
		return nil
	})
	if err != nil {
		t.Fatalf("Traverse returned error: %v", err)
	}

	if visited != len(locations) {
		t.Errorf("Traverse did not invoke the callback for every location")
	}
}
